# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - BarronUnidad3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://barronunidad3acr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3d69dbb99b8e4635a45712e06bd7f31c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8da12856f24d4e92a8aa5f7e765ac0ee }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: barronunidad3acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3d69dbb99b8e4635a45712e06bd7f31c }}/barronunidad327e5:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BarronUnidad3'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b3a3ade8e1d14fef921f54f88c08059e }}
        images: 'barronunidad3acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3d69dbb99b8e4635a45712e06bd7f31c }}/barronunidad327e5:${{ github.sha }}'